services:
  - type: web
    name: phoenix-automotive
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    regions:
      - oregon
    plan: starter
