# Restart Verification Script

echo "🔄 Server Restart Required!"
echo "=========================================="
echo ""
echo "📝 Issue Identified:"
echo "The health endpoint is still returning the old URL:"
echo "  Current: https://phxautogroup.com/api/partsmatrix"
echo "  Expected: https://www.phxautogroup.com/api/partsmatrix"
echo ""
echo "🔧 This means the server needs to be restarted to load the new .env values"
echo ""
echo "🚀 Restart Steps for Different Deployment Methods:"
echo ""
echo "1. If using PM2:"
echo "   pm2 restart all"
echo "   pm2 reload all"
echo ""
echo "2. If using forever:"
echo "   forever restartall"
echo ""
echo "3. If using systemd service:"
echo "   sudo systemctl restart your-app-name"
echo ""
echo "4. If using Docker:"
echo "   docker restart container-name"
echo ""
echo "5. If using Render/Heroku/Vercel:"
echo "   - Push the updated .env file to trigger a redeploy"
echo "   - Or use the platform's restart function"
echo ""
echo "6. If running manually with npm:"
echo "   - Stop the current process (Ctrl+C)"
echo "   - Run: npm start (or npm run start:prod)"
echo ""
echo "✅ After restart, run the test again:"
echo "   node comprehensive-ebay-test.js"
echo ""
echo "🎯 The health endpoint should then show:"
echo "   endpoint: 'https://www.phxautogroup.com/api/partsmatrix'"
